---
- name: reload kernel modules
  systemd:
    name: systemd-modules-load
    state: restarted
  become: yes
- name: restart networking
  systemd:
    name: network
    state: restarted
  become: yes
