---
- name: download calico manifest
  get_url:
    url: https://docs.projectcalico.org/v3.11/manifests/calico.yaml
    dest: "{{ansible_env.HOME}}/calico.yaml"
  environment:
    https_proxy: https://192.168.70.1:8080
- name: install vim
  yum:
    name: vim
    state: latest
  become: yes
- name: pull docker images
  command: kubeadm config images pull
  become: yes
