all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  children:
    masters:
      hosts:
        master:
    nodes:
      hosts:
        node-0:
        node-1:
    vbses:
      hosts:
        vbs-1:
    registries:
      hosts:
        registry:
